"""
Migration Script: Rename landing table columns to documented names.
This script renames columns from cryptic codes to self-documenting names.
"""

import sqlite3
import re
from pathlib import Path

DB_PATH = r"C:\Users\X1Carbon\Documents\Projects\FleetAI\database\fleetai.db"

# Column name mappings for each table
# Format: old_name -> new_name

COLUMN_MAPPINGS = {
    'landing_CCOB': {
        # Object/Vehicle table - 95 columns
        'CCOB_OBOBNO': 'CCOB_OBOBNO_Object_Number',
        'CCOB_OBOBCX': 'CCOB_OBOBCX_Chassis_Number',
        'CCOB_OBMKCD': 'CCOB_OBMKCD_Make_Code',
        'CCOB_OBMDCD': 'CCOB_OBMDCD_Model_Code',
        'CCOB_OBCUNO': 'CCOB_OBCUNO_Customer_Number',
        'CCOB_OBPCNO': 'CCOB_OBPCNO_Profit_Centre_Number',
        'CCOB_OBCONO': 'CCOB_OBCONO_Contract_Number',
        'CCOB_OBCPNO': 'CCOB_OBCPNO_Calculation_Number',
        'CCOB_OBOBIV': 'CCOB_OBOBIV_Driver_Participation_Pct',
        'CCOB_OBUSCD': 'CCOB_OBUSCD_Object_Usage',
        'CCOB_OBCTIC': 'CCOB_OBCTIC_Tech_Control_Date_Century',
        'CCOB_OBCTIY': 'CCOB_OBCTIY_Tech_Control_Date_Year',
        'CCOB_OBCTIM': 'CCOB_OBCTIM_Tech_Control_Date_Month',
        'CCOB_OBCTID': 'CCOB_OBCTID_Tech_Control_Date_Day',
        'CCOB_OBOBUC': 'CCOB_OBOBUC_Upholstery_Color',
        'CCOB_OBOBUP': 'CCOB_OBOBUP_Upholstery_Code',
        'CCOB_OBOBEC': 'CCOB_OBOBEC_Exterior_Color',
        'CCOB_OBOBBC': 'CCOB_OBOBBC_Object_Begin_Date_Century',
        'CCOB_OBOBBY': 'CCOB_OBOBBY_Object_Begin_Date_Year',
        'CCOB_OBOBBM': 'CCOB_OBOBBM_Object_Begin_Date_Month',
        'CCOB_OBOBBD': 'CCOB_OBOBBD_Object_Begin_Date_Day',
        'CCOB_OBOBSK': 'CCOB_OBOBSK_Begin_Mileage',
        'CCOB_OBFUSK': 'CCOB_OBFUSK_Begin_Mileage_Fuel_Incl',
        'CCOB_OBOABC': 'CCOB_OBOABC_Recalc_Start_Date_Century',
        'CCOB_OBOABY': 'CCOB_OBOABY_Recalc_Start_Date_Year',
        'CCOB_OBOABM': 'CCOB_OBOABM_Recalc_Start_Date_Month',
        'CCOB_OBOABD': 'CCOB_OBOABD_Recalc_Start_Date_Day',
        'CCOB_OBMKTY': 'CCOB_OBMKTY_HSN_TSN',
        'CCOB_OBOBSC': 'CCOB_OBOBSC_Object_Status',
        'CCOB_OBSCCM': 'CCOB_OBSCCM_Status_Comment',
        'CCOB_OBRGNO': 'CCOB_OBRGNO_Registration_Number',
        'CCOB_OBRGBC': 'CCOB_OBRGBC_Reg_Begin_Date_Century',
        'CCOB_OBRGBY': 'CCOB_OBRGBY_Reg_Begin_Date_Year',
        'CCOB_OBRGBM': 'CCOB_OBRGBM_Reg_Begin_Date_Month',
        'CCOB_OBRGBD': 'CCOB_OBRGBD_Reg_Begin_Date_Day',
        'CCOB_OBRGEC': 'CCOB_OBRGEC_Reg_End_Date_Century',
        'CCOB_OBRGEY': 'CCOB_OBRGEY_Reg_End_Date_Year',
        'CCOB_OBRGEM': 'CCOB_OBRGEM_Reg_End_Date_Month',
        'CCOB_OBRGED': 'CCOB_OBRGED_Reg_End_Date_Day',
        'CCOB_OBRGPV': 'CCOB_OBRGPV_Previous_Registration',
        'CCOB_OBOBOR': 'CCOB_OBOBOR_Client_Reference',
        'CCOB_OBNDTA': 'CCOB_OBNDTA_Non_Deductable_Taxes',
        'CCOB_OBPRIC': 'CCOB_OBPRIC_Monthly_Rental',
        'CCOB_OBRCOB': 'CCOB_OBRCOB_Replacement_Car_Category',
        'CCOB_OBFSEC': 'CCOB_OBFSEC_Object_End_Date_Century',
        'CCOB_OBFSEY': 'CCOB_OBFSEY_Object_End_Date_Year',
        'CCOB_OBFSEM': 'CCOB_OBFSEM_Object_End_Date_Month',
        'CCOB_OBFSED': 'CCOB_OBFSED_Object_End_Date_Day',
        'CCOB_OBFSDU': 'CCOB_OBFSDU_Budgeted_Months',
        'CCOB_OBFSAM': 'CCOB_OBFSAM_Investment_Amount',
        'CCOB_OBFSRV': 'CCOB_OBFSRV_Budgeted_Residual_Value',
        'CCOB_OBKMDU': 'CCOB_OBKMDU_Total_Budgeted_Mileage',
        'CCOB_OBKMBU': 'CCOB_OBKMBU_Budgeted_Mileage_Per_Year',
        'CCOB_OBOBMC': 'CCOB_OBOBMC_Manufacturing_Date_Century',
        'CCOB_OBOBMY': 'CCOB_OBOBMY_Manufacturing_Date_Year',
        'CCOB_OBOBMM': 'CCOB_OBOBMM_Manufacturing_Date_Month',
        'CCOB_OBOBMD': 'CCOB_OBOBMD_Manufacturing_Date_Day',
        'CCOB_OBTLCD': 'CCOB_OBTLCD_Contract_Type',
        'CCOB_OBLPCD': 'CCOB_OBLPCD_Company_Code',
        'CCOB_OBGRNO': 'CCOB_OBGRNO_Client_Group_Number',
        'CCOB_OBORNO': 'CCOB_OBORNO_Order_Number',
        'CCOB_OBORCD': 'CCOB_OBORCD_Object_Takeover_Code',
        'CCOB_OBDTIC': 'CCOB_OBDTIC_Object_Data_Incomplete',
        'CCOB_OBSLPR': 'CCOB_OBSLPR_Final_Sales_Price',
        'CCOB_OBFLIN': 'CCOB_OBFLIN_Floating_Interest',
        'CCOB_OBRPPD': 'CCOB_OBRPPD_Reporting_Period',
        'CCOB_OBCOUC': 'CCOB_OBCOUC_Country_Code',
        'CCOB_OBVOLC': 'CCOB_OBVOLC_Volume_Measurement',
        'CCOB_OBDISC': 'CCOB_OBDISC_Distance_Measurement',
        'CCOB_OBCONC': 'CCOB_OBCONC_Consumption_Measurement',
        'CCOB_OBCURC': 'CCOB_OBCURC_Currency_Unit',
        'CCOB_OBINCL': 'CCOB_OBINCL_Insurance_Class',
        'CCOB_OBBYCD': 'CCOB_OBBYCD_Buyback_Code',
        'CCOB_OBBJRW': 'CCOB_OBBJRW_Service_Freq_Period',
        'CCOB_OBBIRW': 'CCOB_OBBIRW_Service_Freq_Mileage',
        'CCOB_OBMEPE': 'CCOB_OBMEPE_Timeout_Period_Days',
        'CCOB_OBSLCD': 'CCOB_OBSLCD_Sales_Reason_Code',
        'CCOB_OBOREF': 'CCOB_OBOREF_Object_Reference_Number',
        'CCOB_OBDRPC': 'CCOB_OBDRPC_Driver_Profit_Center',
        'CCOB_OBFUCD': 'CCOB_OBFUCD_Fuel_Code',
        'CCOB_OBOBAC': 'CCOB_OBOBAC_Admission_Date_Century',
        'CCOB_OBOBAY': 'CCOB_OBOBAY_Admission_Date_Year',
        'CCOB_OBOBAM': 'CCOB_OBOBAM_Admission_Date_Month',
        'CCOB_OBOBAD': 'CCOB_OBOBAD_Admission_Date_Day',
        'CCOB_OBOBSN': 'CCOB_OBOBSN_Supplier_Number',
        'CCOB_OBOBSQ': 'CCOB_OBOBSQ_Supplier_Rotation_Number',
        'CCOB_OBOBPU': 'CCOB_OBOBPU_Object_Purchase_Price',
        'CCOB_OBRCDA': 'CCOB_OBRCDA_Replacement_Days',
        'CCOB_OBFSKM': 'CCOB_OBFSKM_Last_Mileage_Known',
        'CCOB_OBKMDD': 'CCOB_OBKMDD_Mileage_Date_Day',
        'CCOB_OBKMMM': 'CCOB_OBKMMM_Mileage_Date_Month',
        'CCOB_OBKMCC': 'CCOB_OBKMCC_Mileage_Date_Century',
        'CCOB_OBKMYY': 'CCOB_OBKMYY_Mileage_Date_Year',
        'CCOB_OBLPPV': 'CCOB_OBLPPV_Previous_Company_Code',
        'CCOB_OBOBMN': 'CCOB_OBOBMN_Motor_Number',
    },
    'landing_CCCU': {
        # Customer table
        'CCCU_CUNULO': 'CCCU_CUNULO_Client_Number',
        'CCCU_CUGNLO': 'CCCU_CUGNLO_Client_Group_Number',
        'CCCU_CUNOLO': 'CCCU_CUNOLO_Name',
        'CCCU_CUNOL2': 'CCCU_CUNOL2_Name_Cont',
        'CCCU_CUNOL3': 'CCCU_CUNOL3_Name_Cont',
        'CCCU_CUCLLO': 'CCCU_CUCLLO_Language_Code',
        'CCCU_CUCPLO': 'CCCU_CUCPLO_Country_Code',
        'CCCU_CUADLO': 'CCCU_CUADLO_Address',
        'CCCU_CULOLO': 'CCCU_CULOLO_Locality',
        'CCCU_CUCALO': 'CCCU_CUCALO_Area_Code',
        'CCCU_CUNTLO': 'CCCU_CUNTLO_Telephone_Number',
        'CCCU_CUNFLO': 'CCCU_CUNFLO_Fax_Number',
        'CCCU_CUNELO': 'CCCU_CUNELO_Email_Address',
        'CCCU_CURPPD': 'CCCU_CURPPD_Reporting_Period',
        'CCCU_CUCOUC': 'CCCU_CUCOUC_Country_Code',
        'CCCU_CURSLO': 'CCCU_CURSLO_Account_Manager',
    },
    'landing_CCDR': {
        # Driver table
        'CCDR_DROBNO': 'CCDR_DROBNO_Object_Number',
        'CCDR_DRDRNO': 'CCDR_DRDRNO_Driver_Number',
        'CCDR_DRACDR': 'CCDR_DRACDR_Actual_Driver_Code',
        'CCDR_DRDRNM': 'CCDR_DRDRNM_Driver_Name',
        'CCDR_DRDRFN': 'CCDR_DRDRFN_Driver_First_Name',
        'CCDR_DRDRLN': 'CCDR_DRDRLN_Driver_Last_Name',
        'CCDR_DRDRAD': 'CCDR_DRDRAD_Driver_Address',
        'CCDR_DRDRLO': 'CCDR_DRDRLO_Driver_Locality',
        'CCDR_DRDRLA': 'CCDR_DRDRLA_Driver_Country_Code',
        'CCDR_DRPVTF': 'CCDR_DRPVTF_Private_Telephone',
        'CCDR_DROFTF': 'CCDR_DROFTF_Office_Telephone',
        'CCDR_DRPVNF': 'CCDR_DRPVNF_Mobile_Phone',
        'CCDR_DRDRNE': 'CCDR_DRDRNE_Email',
        'CCDR_DRRPPD': 'CCDR_DRRPPD_Reporting_Period',
        'CCDR_DRCOUC': 'CCDR_DRCOUC_Country_Code',
    },
    'landing_CCAU': {
        # Automobile reference table
        'CCAU_AUMKCD': 'CCAU_AUMKCD_Make_Code',
        'CCAU_AUMKDS': 'CCAU_AUMKDS_Make_Description',
        'CCAU_AUMDCD': 'CCAU_AUMDCD_Model_Code',
        'CCAU_AUMDDS': 'CCAU_AUMDDS_Model_Description',
        'CCAU_AUMDGH': 'CCAU_AUMDGH_Model_Group_High',
        'CCAU_AUMDGR': 'CCAU_AUMDGR_Model_Group_Range',
        'CCAU_AUMDGS': 'CCAU_AUMDGS_Model_Group_Size',
        'CCAU_AUTYDS': 'CCAU_AUTYDS_Type_Description',
        'CCAU_AURPPD': 'CCAU_AURPPD_Reporting_Period',
        'CCAU_AUCOUC': 'CCAU_AUCOUC_Country_Code',
    },
    'landing_CCGD': {
        # Odometer/Mileage history table
        'CCGD_MAOBNO': 'CCGD_MAOBNO_Object_Number',
        'CCGD_MAGDSQ': 'CCGD_MAGDSQ_Mileage_Sequence',
        'CCGD_MAGDCC': 'CCGD_MAGDCC_Mileage_Date_Century',
        'CCGD_MAGDYY': 'CCGD_MAGDYY_Mileage_Date_Year',
        'CCGD_MAGDMM': 'CCGD_MAGDMM_Mileage_Date_Month',
        'CCGD_MAGDDD': 'CCGD_MAGDDD_Mileage_Date_Day',
        'CCGD_MAGDKM': 'CCGD_MAGDKM_Mileage_Km',
        'CCGD_MAGDAM': 'CCGD_MAGDAM_Mileage_Amount',
        'CCGD_MAGDDS': 'CCGD_MAGDDS_Mileage_Description',
        'CCGD_MAGDSC': 'CCGD_MAGDSC_Mileage_Source_Code',
        'CCGD_MANUFO': 'CCGD_MANUFO_Supplier_Number',
        'CCGD_MANAFO': 'CCGD_MANAFO_Supplier_Reference',
    },
    'landing_CCCP': {
        # Contract position table
        'CCCP_CPCPNO': 'CCCP_CPCPNO_Contract_Position_Number',
        'CCCP_CPGNLO': 'CCCP_CPGNLO_Group_Name',
        'CCCP_CPCUNO': 'CCCP_CPCUNO_Customer_Number',
        'CCCP_CPPCNO': 'CCCP_CPPCNO_Profit_Center_Number',
        'CCCP_CPCONO': 'CCCP_CPCONO_Contract_Number',
        'CCCP_CPACCP': 'CCCP_CPACCP_Active_Contract_Position',
        'CCCP_CPCPDL': 'CCCP_CPCPDL_Delivery_Days',
        'CCCP_CPCPDU': 'CCCP_CPCPDU_Contract_Duration_Months',
        'CCCP_CPCPMI': 'CCCP_CPCPMI_Km_Per_Year',
        'CCCP_CPCPPU': 'CCCP_CPCPPU_Purchase_Price',
        'CCCP_CPCPRV': 'CCCP_CPCPRV_Residual_Value',
        'CCCP_CPCPTA': 'CCCP_CPCPTA_Total_Amount',
        'CCCP_CPIRPT': 'CCCP_CPIRPT_Interest_Rate_Percent',
        'CCCP_CPMKCD': 'CCCP_CPMKCD_Make_Code',
        'CCCP_CPMDCD': 'CCCP_CPMDCD_Model_Code',
        'CCCP_CPMRAA': 'CCCP_CPMRAA_Monthly_Rate_Admin',
        'CCCP_CPMRAF': 'CCCP_CPMRAF_Monthly_Rate_Fuel',
        'CCCP_CPMRDP': 'CCCP_CPMRDP_Monthly_Rate_Depreciation',
        'CCCP_CPMRIN': 'CCCP_CPMRIN_Monthly_Rate_Insurance',
        'CCCP_CPMRIR': 'CCCP_CPMRIR_Monthly_Rate_Interest',
        'CCCP_CPMRMF': 'CCCP_CPMRMF_Monthly_Rate_Maintenance',
        'CCCP_CPMRRA': 'CCCP_CPMRRA_Monthly_Rate_Replacement',
        'CCCP_CPMRRO': 'CCCP_CPMRRO_Monthly_Rate_Road_Tax',
        'CCCP_CPMRVI': 'CCCP_CPMRVI_Monthly_Rate_Tires',
        'CCCP_CPMTCT': 'CCCP_CPMTCT_Monthly_Total_Cost',
        'CCCP_CPUNMA': 'CCCP_CPUNMA_Unit_Rate_Maintenance',
        'CCCP_CPUNTR': 'CCCP_CPUNTR_Unit_Rate_Tires',
        'CCCP_CPUNRC': 'CCCP_CPUNRC_Unit_Rate_Replacement',
        'CCCP_CPXMPT': 'CCCP_CPXMPT_Excess_Km_Rate',
        'CCCP_CPRPPD': 'CCCP_CPRPPD_Reporting_Period',
        'CCCP_CPCOUC': 'CCCP_CPCOUC_Country_Code',
        'CCCP_CPLPCD': 'CCCP_CPLPCD_Lease_Type_Code',
    },
    'landing_CCBI': {
        # Billing table
        'CCBI_BIBINO': 'CCBI_BIBINO_Billing_Number',
        'CCBI_BIOBNO': 'CCBI_BIOBNO_Object_Number',
        'CCBI_BIBIRN': 'CCBI_BIBIRN_Billing_Run_Number',
        'CCBI_BIBIAO': 'CCBI_BIBIAO_Billing_Account_Owner',
        'CCBI_BIBINM': 'CCBI_BIBINM_Billing_Name',
        'CCBI_BIBIAD': 'CCBI_BIBIAD_Billing_Address',
        'CCBI_BIBILO': 'CCBI_BIBILO_Billing_Locality',
        'CCBI_BIBICM': 'CCBI_BIBICM_Billing_Method',
        'CCBI_BIBIA1': 'CCBI_BIBIA1_Billing_Amount_1',
        'CCBI_BIBIAV': 'CCBI_BIBIAV_Billing_Amount_Variable',
        'CCBI_BIBIAM': 'CCBI_BIBIAM_Billing_Amount_Monthly',
        'CCBI_BIBIPL': 'CCBI_BIBIPL_Billing_Period_Length',
        'CCBI_BICURC': 'CCBI_BICURC_Currency_Code',
        'CCBI_BIRPPD': 'CCBI_BIRPPD_Reporting_Period',
        'CCBI_BICOUC': 'CCBI_BICOUC_Country_Code',
    },
    'landing_CCGR': {
        # Groups table
        'CCGR_GRGNLO': 'CCGR_GRGNLO_Group_Number',
        'CCGR_GRNKLO': 'CCGR_GRNKLO_Customer_Number',
        'CCGR_GRNOLO': 'CCGR_GRNOLO_Group_Name',
        'CCGR_GRRPPD': 'CCGR_GRRPPD_Reporting_Period',
        'CCGR_GRCOUC': 'CCGR_GRCOUC_Country_Code',
    },
    'landing_CCOR': {
        # Orders table
        'CCOR_ORORNO': 'CCOR_ORORNO_Order_Number',
        'CCOR_ORCPNO': 'CCOR_ORCPNO_Contract_Position_Number',
        'CCOR_ORGNLO': 'CCOR_ORGNLO_Group_Name',
        'CCOR_ORCUNO': 'CCOR_ORCUNO_Customer_Number',
        'CCOR_ORPCNO': 'CCOR_ORPCNO_Profit_Center_Number',
        'CCOR_ORCONO': 'CCOR_ORCONO_Contract_Number',
        'CCOR_ORORSC': 'CCOR_ORORSC_Order_Status_Code',
        'CCOR_ORNUFO': 'CCOR_ORNUFO_Supplier_Number',
        'CCOR_ORNAFO': 'CCOR_ORNAFO_Supplier_Amount',
        'CCOR_ORRPPD': 'CCOR_ORRPPD_Reporting_Period',
        'CCOR_ORCOUC': 'CCOR_ORCOUC_Country_Code',
    },
    'landing_CCDT': {
        # Domain text table
        'DTCYCD': 'CCDT_DTCYCD_Country_Code',
        'DTDMID': 'CCDT_DTDMID_Domain_ID',
        'DTDMVA': 'CCDT_DTDMVA_Domain_Value',
        'DTDMLN': 'CCDT_DTDMLN_Language_Code',
        'DTDMTX': 'CCDT_DTDMTX_Domain_Text',
    },
    'landing_CCES': {
        # Service table
        'ESCUNO': 'CCES_ESCUNO_Customer_No',
        'ESPCNO': 'CCES_ESPCNO_Contract_Position_No',
        'ESOBNO': 'CCES_ESOBNO_Object_No',
        'ESESSQ': 'CCES_ESESSQ_Service_Sequence',
        'ESESCD': 'CCES_ESESCD_Service_Code',
        'ESESCT': 'CCES_ESESCT_Service_Cost_Total',
        'ESESIV': 'CCES_ESESIV_Service_Invoice',
        'ESIVSU': 'CCES_ESIVSU_Invoice_Supplier',
        'ESTMCT': 'CCES_ESTMCT_Total_Monthly_Cost',
        'ESTMIV': 'CCES_ESTMIV_Total_Monthly_Invoice',
        'ESLPCD': 'CCES_ESLPCD_LP_Code',
        'ESRPPD': 'CCES_ESRPPD_Reporting_Period',
        'ESCOUC': 'CCES_ESCOUC_Country_Code',
        'ESVOLC': 'CCES_ESVOLC_Volume_Code',
        'ESDISC': 'CCES_ESDISC_Distance_Code',
        'ESCONC': 'CCES_ESCONC_Consumption_Code',
        'ESCURC': 'CCES_ESCURC_Currency_Code',
    },
    'landing_CCMS': {
        # Maintenance table
        'MSOBNO': 'CCMS_MSOBNO_Object_No',
        'MSGDSQ': 'CCMS_MSGDSQ_Sequence',
        'MSGDCC': 'CCMS_MSGDCC_Date_Century',
        'MSGDYY': 'CCMS_MSGDYY_Date_Year',
        'MSGDMM': 'CCMS_MSGDMM_Date_Month',
        'MSGDDD': 'CCMS_MSGDDD_Date_Day',
        'MSGDKM': 'CCMS_MSGDKM_Mileage_Km',
        'MSGDAM': 'CCMS_MSGDAM_Amount',
        'MSGDDS': 'CCMS_MSGDDS_Description',
        'MSGDD2': 'CCMS_MSGDD2_Description_2',
        'MSGDD3': 'CCMS_MSGDD3_Description_3',
        'MSGDSC': 'CCMS_MSGDSC_Source_Code',
        'MSMSTY': 'CCMS_MSMSTY_Maintenance_Type',
        'MSNUFO': 'CCMS_MSNUFO_Supplier_No',
        'MSNAFO': 'CCMS_MSNAFO_Supplier_Branch',
        'MSMJCD': 'CCMS_MSMJCD_Major_Code',
        'MSMNCD': 'CCMS_MSMNCD_Minor_Code',
        'MSRPPD': 'CCMS_MSRPPD_Reporting_Period',
        'MSCOUC': 'CCMS_MSCOUC_Country_Code',
        'MSVOLC': 'CCMS_MSVOLC_Volume_Code',
        'MSDISC': 'CCMS_MSDISC_Distance_Code',
        'MSCONC': 'CCMS_MSCONC_Consumption_Code',
        'MSCURC': 'CCMS_MSCURC_Currency_Code',
        'MSSIRN': 'CCMS_MSSIRN_SI_Run_No',
        'MSDAFC': 'CCMS_MSDAFC_Approval_Date_Century',
        'MSDAFY': 'CCMS_MSDAFY_Approval_Date_Year',
        'MSDAFM': 'CCMS_MSDAFM_Approval_Date_Month',
        'MSDAFD': 'CCMS_MSDAFD_Approval_Date_Day',
    },
    'landing_CCPI': {
        # PI table
        'PICONO': 'CCPI_PICONO_Contract_No',
        'PICUNO': 'CCPI_PICUNO_Customer_No',
        'PINACD': 'CCPI_PINACD_Name_Code',
        'PIOBNO': 'CCPI_PIOBNO_Object_No',
        'PIPCNO': 'CCPI_PIPCNO_Contract_Position_No',
        'PIPIAM': 'CCPI_PIPIAM_Amount',
        'PIPICD': 'CCPI_PIPICD_Cost_Code',
        'PIEBRP': 'CCPI_PIEBRP_EB_Reporting_Period',
        'PIPIDR': 'CCPI_PIPIDR_Driver_No',
        'PIPIDS': 'CCPI_PIPIDS_Description',
        'PIPIGR': 'CCPI_PIPIGR_Gross_Net',
        'PIPIIV': 'CCPI_PIPIIV_Invoice_No',
        'PIPILP': 'CCPI_PIPILP_LP_Code',
        'PIPIOB': 'CCPI_PIPIOB_Object_Bridge',
        'PIPIOR': 'CCPI_PIPIOR_Origin_Code',
        'PIPIRN': 'CCPI_PIPIRN_Run_No',
        'PIPISC': 'CCPI_PIPISC_Source_Code',
        'PIPIVT': 'CCPI_PIPIVT_VAT_Type',
        'PIRPPD': 'CCPI_PIRPPD_Reporting_Period',
        'PICOUC': 'CCPI_PICOUC_Country_Code',
    },
    'landing_CCRC': {
        # Replacement car table
        'RCOBNO': 'CCRC_RCOBNO_Object_No',
        'RCRCNO': 'CCRC_RCRCNO_RC_No',
        'RCRCSQ': 'CCRC_RCRCSQ_Sequence',
        'RCDRNO': 'CCRC_RCDRNO_Driver_No',
        'RCRCRN': 'CCRC_RCRCRN_RC_Run_No',
        'RCRCBC': 'CCRC_RCRCBC_Begin_Date_Century',
        'RCRCBY': 'CCRC_RCRCBY_Begin_Date_Year',
        'RCRCBM': 'CCRC_RCRCBM_Begin_Date_Month',
        'RCRCBD': 'CCRC_RCRCBD_Begin_Date_Day',
        'RCRCEC': 'CCRC_RCRCEC_End_Date_Century',
        'RCRCEY': 'CCRC_RCRCEY_End_Date_Year',
        'RCRCEM': 'CCRC_RCRCEM_End_Date_Month',
        'RCRCED': 'CCRC_RCRCED_End_Date_Day',
        'RCRCCD': 'CCRC_RCRCCD_RC_Code',
        'RCRCKM': 'CCRC_RCRCKM_Km',
        'RCRCAM': 'CCRC_RCRCAM_Amount',
        'RCRCRS': 'CCRC_RCRCRS_Reason',
        'RCRCDS': 'CCRC_RCRCDS_Description',
        'RCRCD2': 'CCRC_RCRCD2_Description_2',
        'RCRCD3': 'CCRC_RCRCD3_Description_3',
        'RCRCTY': 'CCRC_RCRCTY_Type',
        'RCRCDR': 'CCRC_RCRCDR_Driver_Name',
        'RCRCSC': 'CCRC_RCRCSC_Source_Code',
        'RCRPPD': 'CCRC_RCRPPD_Reporting_Period',
        'RCCOUC': 'CCRC_RCCOUC_Country_Code',
    },
    'landing_CCRP': {
        # Reporting period table
        'RPRPCC': 'CCRP_RPRPCC_Period_CC',
        'RPRPYY': 'CCRP_RPRPYY_Period_YY',
        'RPRPMM': 'CCRP_RPRPMM_Period_MM',
        'RPRPDD': 'CCRP_RPRPDD_Period_DD',
        'RPRPPD': 'CCRP_RPRPPD_Reporting_Period',
        'RPMTPD': 'CCRP_RPMTPD_Month_Period',
    },
    'landing_CCSU': {
        # Supplier table
        'SUNUFO': 'CCSU_SUNUFO_Supplier_No',
        'SUNAFO': 'CCSU_SUNAFO_Branch_No',
        'SUNOFO': 'CCSU_SUNOFO_Supplier_Name',
        'SUNOF2': 'CCSU_SUNOF2_Name_Line_2',
        'SUNOF3': 'CCSU_SUNOF3_Name_Line_3',
        'SUCLFO': 'CCSU_SUCLFO_Class',
        'SUCPFO': 'CCSU_SUCPFO_Country_Code',
        'SUADFO': 'CCSU_SUADFO_Address',
        'SULOFO': 'CCSU_SULOFO_City',
        'SUCAFO': 'CCSU_SUCAFO_Category',
        'SUNTFO': 'CCSU_SUNTFO_Phone',
        'SUNFFO': 'CCSU_SUNFFO_Fax',
        'SUNEFO': 'CCSU_SUNEFO_Email',
        'SUCTFO': 'CCSU_SUCTFO_Contact_Person',
        'SURSFO': 'CCSU_SURSFO_Responsible_Person',
        'SURPPD': 'CCSU_SURPPD_Reporting_Period',
        'SUCOUC': 'CCSU_SUCOUC_Country',
    },
    'landing_CCCR': {
        # Cost report table
        'CROBNO': 'CCCR_CROBNO_Object_No',
        'CRBEAM': 'CCCR_CRBEAM_Book_Value_Begin_Amount',
        'CRBELT': 'CCCR_CRBELT_Book_Value_Begin_LT',
        'CRDIAM': 'CCCR_CRDIAM_Disinvestment_Amount',
        'CRDILT': 'CCCR_CRDILT_Disinvestment_LT',
        'CRGAAM': 'CCCR_CRGAAM_Gain_Amount',
        'CRGALT': 'CCCR_CRGALT_Gain_LT',
        'CRFSBV': 'CCCR_CRFSBV_First_Start_Book_Value',
        'CRFSIR': 'CCCR_CRFSIR_First_Start_Interest_Rate',
        'CRFUCT': 'CCCR_CRFUCT_Fuel_Cost_Total',
        'CRMACT': 'CCCR_CRMACT_Maintenance_Cost_Total',
        'CRRCCT': 'CCCR_CRRCCT_Replacement_Car_Cost_Total',
        'CRTRCT': 'CCCR_CRTRCT_Tyre_Cost_Total',
        'CRFUIV': 'CCCR_CRFUIV_Fuel_Invoice_Total',
        'CRMAIV': 'CCCR_CRMAIV_Maintenance_Invoice_Total',
        'CRRCIV': 'CCCR_CRRCIV_Replacement_Car_Invoice_Total',
        'CRTRIV': 'CCCR_CRTRIV_Tyre_Invoice_Total',
        'CRFSKM': 'CCCR_CRFSKM_First_Start_Km',
        'CRKMCC': 'CCCR_CRKMCC_Odometer_Date_Century',
        'CRKMYY': 'CCCR_CRKMYY_Odometer_Date_Year',
        'CRKMMM': 'CCCR_CRKMMM_Odometer_Date_Month',
        'CRKMDD': 'CCCR_CRKMDD_Odometer_Date_Day',
        'CRFSIK': 'CCCR_CRFSIK_First_Start_Initial_Km',
        'CRKMDR': 'CCCR_CRKMDR_Km_Driven',
        'CRMMDR': 'CCCR_CRMMDR_Monthly_Km_Driven',
        'CRKMTE': 'CCCR_CRKMTE_Km_Technical',
        'CRFUCK': 'CCCR_CRFUCK_Fuel_Cost_Per_Km',
        'CRFUIK': 'CCCR_CRFUIK_Fuel_Invoice_Per_Km',
        'CRRECO': 'CCCR_CRRECO_Fuel_Consumption',
        'CRFUSL': 'CCCR_CRFUSL_Fuel_Slope',
        'CRFUMD': 'CCCR_CRFUMD_Fuel_Monthly_Deviation',
        'CRMACK': 'CCCR_CRMACK_Maintenance_Cost_Per_Km',
        'CRMAIK': 'CCCR_CRMAIK_Maintenance_Invoice_Per_Km',
        'CRMASL': 'CCCR_CRMASL_Maintenance_Slope',
        'CRMAMD': 'CCCR_CRMAMD_Maintenance_Monthly_Deviation',
        'CRRCCK': 'CCCR_CRRCCK_RC_Cost_Per_Km',
        'CRRCIK': 'CCCR_CRRCIK_RC_Invoice_Per_Km',
        'CRRCSL': 'CCCR_CRRCSL_RC_Slope',
        'CRRCMD': 'CCCR_CRRCMD_RC_Monthly_Deviation',
        'CRRCKM': 'CCCR_CRRCKM_RC_Km',
        'CRRCAM': 'CCCR_CRRCAM_RC_Amount',
        'CRTRCK': 'CCCR_CRTRCK_Tyre_Cost_Per_Km',
        'CRTRIK': 'CCCR_CRTRIK_Tyre_Invoice_Per_Km',
        'CRTRSL': 'CCCR_CRTRSL_Tyre_Slope',
        'CRTRMD': 'CCCR_CRTRMD_Tyre_Monthly_Deviation',
        'CRTOCT': 'CCCR_CRTOCT_Total_Cost',
        'CRTOIV': 'CCCR_CRTOIV_Total_Invoiced',
        'CRCTKM': 'CCCR_CRCTKM_Cost_Per_Km',
        'CRTOSU': 'CCCR_CRTOSU_Total_Surplus',
        'CRTOSA': 'CCCR_CRTOSA_Total_Surplus_Absolute',
        'CRTOTO': 'CCCR_CRTOTO_Total_Total',
        'CRLWKM': 'CCCR_CRLWKM_Last_Week_Km',
        'CRUPKM': 'CCCR_CRUPKM_Update_Km',
        'CRMANR': 'CCCR_CRMANR_Maintenance_Count',
        'CRFUNR': 'CCCR_CRFUNR_Fuel_Count',
        'CRRCNR': 'CCCR_CRRCNR_RC_Count',
        'CRTRNR': 'CCCR_CRTRNR_Tyre_Count',
        'CRTNNR': 'CCCR_CRTNNR_Tyre_New_Count',
        'CRTWNR': 'CCCR_CRTWNR_Tyre_Winter_Count',
        'CRPRKT': 'CCCR_CRPRKT_Private_Km_Pct',
        'CRDANB': 'CCCR_CRDANB_Damage_Count',
        'CRDARE': 'CCCR_CRDARE_Damage_Reserve',
        'CRSG01': 'CCCR_CRSG01_Segment_01',
        'CRSG02': 'CCCR_CRSG02_Segment_02',
        'CRSG03': 'CCCR_CRSG03_Segment_03',
        'CRSG04': 'CCCR_CRSG04_Segment_04',
        'CRSG05': 'CCCR_CRSG05_Segment_05',
        'CRSG06': 'CCCR_CRSG06_Segment_06',
        'CRSG07': 'CCCR_CRSG07_Segment_07',
        'CRSG08': 'CCCR_CRSG08_Segment_08',
        'CRSG09': 'CCCR_CRSG09_Segment_09',
        'CRSG10': 'CCCR_CRSG10_Segment_10',
        'CRSG11': 'CCCR_CRSG11_Segment_11',
        'CRSG12': 'CCCR_CRSG12_Segment_12',
        'CRSG13': 'CCCR_CRSG13_Segment_13',
        'CRSG14': 'CCCR_CRSG14_Segment_14',
        'CRSG15': 'CCCR_CRSG15_Segment_15',
        'CRRPPD': 'CCCR_CRRPPD_Reporting_Period',
        'CRCOUC': 'CCCR_CRCOUC_Country_Code',
        'CRVOLC': 'CCCR_CRVOLC_Volume_Code',
        'CRDISC': 'CCCR_CRDISC_Distance_Code',
        'CRCONC': 'CCCR_CRCONC_Consumption_Code',
        'CRCURC': 'CCCR_CRCURC_Currency_Code',
        'CRMIAM': 'CCCR_CRMIAM_Misc_Insurance_Amount',
        'CRMIPY': 'CCCR_CRMIPY_Misc_Insurance_PerYear',
        'CRMIRN': 'CCCR_CRMIRN_Misc_Insurance_Run_No',
        'CRTSAM': 'CCCR_CRTSAM_Misc_TS_Amount',
        'CRTSPY': 'CCCR_CRTSPY_Misc_TS_PerYear',
        'CRTSRN': 'CCCR_CRTSRN_Misc_TS_Run_No',
        'CRTRNO': 'CCCR_CRTRNO_Traffic_Fines_No',
        'CRPACT': 'CCCR_CRPACT_Parking_Cost_Total',
        'CRPAIV': 'CCCR_CRPAIV_Parking_Invoice_Total',
        'CRPAMD': 'CCCR_CRPAMD_Parking_Monthly_Deviation',
        'CRPASL': 'CCCR_CRPASL_Parking_Slope',
        'CRUNCT': 'CCCR_CRUNCT_Unspecified_Cost_Total',
        'CRUNIV': 'CCCR_CRUNIV_Unspecified_Invoice_Total',
        'CRUNMD': 'CCCR_CRUNMD_Unspecified_Monthly_Deviation',
        'CRUNSL': 'CCCR_CRUNSL_Unspecified_Slope',
        'CRWACT': 'CCCR_CRWACT_Warranty_Cost_Total',
        'CRWAIV': 'CCCR_CRWAIV_Warranty_Invoice_Total',
        'CRWAMD': 'CCCR_CRWAMD_Warranty_Monthly_Deviation',
        'CRWASL': 'CCCR_CRWASL_Warranty_Slope',
    },
}


def rename_table_columns(conn, table_name, mapping):
    """Rename columns in a table using SQLite's ALTER TABLE."""
    cursor = conn.cursor()

    # Get current columns
    cursor.execute(f"PRAGMA table_info({table_name})")
    current_cols = {col[1]: col for col in cursor.fetchall()}

    renamed = 0
    for old_name, new_name in mapping.items():
        if old_name in current_cols and old_name != new_name:
            try:
                cursor.execute(f"ALTER TABLE {table_name} RENAME COLUMN {old_name} TO {new_name}")
                renamed += 1
            except sqlite3.OperationalError as e:
                if "no such column" in str(e).lower():
                    pass  # Column doesn't exist, skip
                else:
                    print(f"    Warning: Could not rename {old_name}: {e}")

    conn.commit()
    return renamed


def migrate_landing_tables():
    """Migrate all landing tables to use documented column names."""
    print("=" * 60)
    print("Landing Table Column Migration")
    print("=" * 60)
    print(f"Database: {DB_PATH}")
    print()

    conn = sqlite3.connect(DB_PATH)

    total_renamed = 0
    for table_name, mapping in COLUMN_MAPPINGS.items():
        print(f"Migrating {table_name}...")
        renamed = rename_table_columns(conn, table_name, mapping)
        print(f"  Renamed {renamed} columns")
        total_renamed += renamed

    conn.close()

    print()
    print(f"Total columns renamed: {total_renamed}")
    print("Migration complete!")


if __name__ == "__main__":
    migrate_landing_tables()
